### ISSUE TITLE
code as comment.

### ISSUE THREAD

**Issue by amirfahoum** [WebAhead5/tudoBom#10]
on all over your scripts  you have dead code like
  // document.getElementById("dateBtn").addEventListener('click', function() { 
    //     var dateSort = function(a, b) {return a.added - b.added}
    //     var newState = todoFunctions.sortTodos(state, dateSort)
    //     update(newState);
    //     })

**Comment by Karyum** [comment]
https://github.com/WebAhead5/tudoBom/blob/master/tests/test.js#L77-L99

**Comment by MoradAbed** [comment]
We'll delete unnecessary code lines. thanks
